apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alerting-service
  template:
    metadata:
      labels:
        app: alerting-service
    spec:
      containers:
        - name: alerting-service
          image: alerting-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: alerting-service
spec:
  selector:
    app: alerting-service
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP
